[build]
  command = "cd admin-dashboard && rm -rf node_modules package-lock.json && npm install --legacy-peer-deps && npm run build"
  publish = "admin-dashboard/build"
  
[build.environment]
  NODE_VERSION = "20"

[functions]
  directory = "admin-dashboard/netlify/functions"

# Redirect API calls to serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Handle React Router (SPA fallback)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18" 